{% set version = "0.15.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-globals
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/globals_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/globals/globals_{{ version }}.tar.gz
  sha256: f83689a420590b0d62b049c40a944c1c8c7202b3f1cc12102712c63104e99496

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-codetools
  run:
    - r-base
    - r-codetools

test:
  commands:
    - $R -e "library('globals')"           # [not win]
    - "\"%R%\" -e \"library('globals')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/globals
  license: LGPL-2.1-or-later
  summary: Identifies global ("unknown" or "free") objects in R expressions by code inspection using various strategies, e.g. conservative or liberal. The objective of this package is to make it as simple as possible to identify global objects for the purpose of exporting them in distributed compute environments.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: globals
# Version: 0.12.5
# Depends: R (>= 3.1.2)
# Imports: codetools
# Title: Identify Global Objects in R Expressions
# Authors@R: c( person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email="henrikb@braju.com"))
# Description: Identifies global ("unknown" or "free") objects in R expressions by code inspection using various strategies, e.g. conservative or liberal. The objective of this package is to make it as simple as possible to identify global objects for the purpose of exporting them in distributed compute environments.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/globals
# BugReports: https://github.com/HenrikBengtsson/globals/issues
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2019-12-07 20:32:40 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2019-12-07 21:10:02 UTC
