# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Gtdqb8HLD7zTCG7eekuvesrOwLzX15CtlRSo2eQ/popkJ6nj3CLxcZdFEIsVN65xsJkcXq2OOnGNAI5LotTT4AYleCUex0TL89vqj0t5ujJqHiRO3a94ulxE252eddBgAvgkFFYbdg0HdQiSbJ6CUJY/z7x2XLSeZUsbcAW8pmGasU8ZF5IS06MMFDVJ6tUAA09soiZDuB66L8Z+yVleDdA8GXaB2iykIWmYin/rhrR5u5ric4zZLIBAzUmEXqya04K6D9r5NzaerGesgr30S1AkxMPW4cQoh/2fJn6j/C4S1ZAOR/V0v9SWZN6XMslaCkG+au63yY5ovgo+QQg7jQGTTHHCCL5pSKL5vd7I6ALxL+X2UptRA9p9Fv8qgSV6oB2ZqGMcRFStJMLVOlW5RVRwCLlj9Jhh2t2qubBqjFuzUsmkk/56xhIcxDMdCfH97kLOMK/VJlrcdci4/IBlDnSOMuTYXhfdg4dY6mYb+84GUerPlLYhlMI+fcLBAWFUm0+HR8jinWIFhZ2CE27vrBUZBzSCvNjJ70YQ2Pg9XkPyTP8QmjW43YpcaWXUCiQUAGhUODSez8kUDs7L/vDpjxeISZBNd5SVKVf3bHPneiE+sgyi2++luBUBOxx6atwVMWZ5vSjv+wVvfigat/AHqzVJB0Tph7ebl8FAgvjVFIU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
